ALTER TABLE tournaments
  ADD COLUMN IF NOT EXISTS sets_to_win       INT     NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS advantage_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS points_to_win     INT     NOT NULL DEFAULT 11;
